/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StCollapsable {
    'collapsableId': string;
    'collapsed': boolean;
    'toggle': (triggerElement?: any) => void;
  }
  interface StCollapsableAttributes extends StencilHTMLAttributes {
    'collapsableId'?: string;
    'collapsed'?: boolean;
    'onCollapseHandler'?: (event: CustomEvent) => void;
    'onExpandHandler'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StCollapsable': Components.StCollapsable;
  }

  interface StencilIntrinsicElements {
    'st-collapsable': Components.StCollapsableAttributes;
  }


  interface HTMLStCollapsableElement extends Components.StCollapsable, HTMLStencilElement {}
  var HTMLStCollapsableElement: {
    prototype: HTMLStCollapsableElement;
    new (): HTMLStCollapsableElement;
  };

  interface HTMLElementTagNameMap {
    'st-collapsable': HTMLStCollapsableElement
  }

  interface ElementTagNameMap {
    'st-collapsable': HTMLStCollapsableElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
